{% set name = "superflore" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros-infrastructure/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f390dfa72d7da87b1362e9b0ac583203c9ad93b00cf0c2e1e880b4c4a62af585

build:
  number: 1
  skip: true  # [py2k]
  entry_points:
    - superflore-gen-ebuilds = superflore.generators.ebuild:main
    - superflore-gen-oe-recipes = superflore.generators.bitbake:main
    - superflore-check-ebuilds = superflore.test_integration.gentoo:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - git
    - pywin32  # [win]
    - beautifulsoup4
    - catkin_pkg >=0.4.0
    - docker-py
    - gitpython
    - pygithub
    - python
    - pyyaml
    - requests
    - rosdep >=0.15.2
    - rosdistro >=0.7.4
    - rosinstall_generator
    - rospkg >=1.1.8
    - setuptools
    - termcolor
    - xmltodict

test:
  imports:
    - superflore
    - superflore.generators
    - superflore.generators.bitbake
    - superflore.generators.ebuild
    - superflore.test_integration
    - superflore.test_integration.gentoo
  commands:
    - superflore-gen-ebuilds --help
    - superflore-gen-oe-recipes --help

about:
  home: https://github.com/ros-infrastructure/superflore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Super Bloom. An extended platform release manager for Robot Operating System.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - allenh1
